### ISSUE TITLE
Default hotkeys intervenes with national keyboard

### ISSUE THREAD

**Issue by taniotanio7** [glutanimate/image-occlusion-enhanced#101]
## Prerequisite checklist

* [ ] In case of a bug: Have you tried restarting Anki?
* [x] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [x] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [x] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

The default hotkey ALT + O (for creating new notes) interrupts national keybind used to write a specific letter (in my case: Polish letter ó) even when making non image-occlusion notes.

## How can we reproduce the problem?

Press ALT + O

**Expected behavior:** Writing national letter

**Actual behavior:** Image Occlusion window pops up

## Version information

**Anki** 2.0.52
Qt 4.8.2 PyQt 4.9.4

**System**

- Operating system: macOS
- Version: Mojave

## Additional suggestions
A way to disable this problematic hotkey would be great...
Unfortunately to use Anki I have to uninstall and reinstall Image Occlusion plugin every time or use CTRL+C and CTRL+V to copy the key from another app.

**Comment by glutanimate** [comment]
Hi Tanio. Please give the latest alpha for Anki 2.1 a try. The hotkey there is customizable and set to Ctrl+Shift+O by default. The 2.0 version will likely not see any more updates in the future, I'm afraid.
