### ISSUE TITLE
Random cards appear blank on ankidroid

### ISSUE THREAD

**Issue by zoliaaz** [glutanimate/image-occlusion-enhanced#102]
## Prerequisite checklist

* [x] In case of a bug: Have you tried restarting Anki?
* [x] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [x] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [x] Did you perform a cursory search through the existing issue reports?

## What is the problem?

Hello, I use image occlusion for almost a year on desktop and android. Most of the time it's working good but sometime it creates cards that's only working on desktop, those cards appear blank on ankidroid. 
![Screenshot Computeur](https://user-images.githubusercontent.com/28677789/57013568-674cbb00-6c0c-11e9-85fc-4e5a8de5811a.jpg)
![Screenshot_Ankidroid](https://user-images.githubusercontent.com/28677789/57013588-7e8ba880-6c0c-11e9-8c67-0180b7c9a376.png)

I did search for the difference between cards that work and those that don't. I tried to change file type (png, jpeg), the size, remove letter with accent in any field ; nothing worked.
I tried [Fix Old Image Occlusion 2.0 Cards](https://ankiweb.net/shared/info/1048682320) add-on, but there was zero card to fix.

I searched over internet but i found nothing.
I couldn't test it on another android devise.
I join you the card  that i presented with screenshot.
[Exemple of card that dont work on ankidroid (image occlusion).zip](https://github.com/glutanimate/image-occlusion-enhanced/files/3134367/Exemple.of.card.that.dont.work.on.ankidroid.image.occlusion.zip)

Thank for the help in advance.
PS: sorry for my bad english, it's not my native language.
## Version information

**Anki**
Version 2.0.52
Qt 4.8.4 PyQt 4.10

**System**
* Android 7.1.2 N2G47H (on Redmi 4A, with MIUI global 10.2.1)
* windows 10

**Comment by zoliaaz** [comment]
I did find the problem, it's because the image title got an apostrophe.

**Comment by glutanimate** [comment]
Thanks for letting me know @zoliaaz. I've subscribed to the issue report in ankidroid and will chime in if I can think of any way I can help
