### ISSUE TITLE
Unable to use/find "hide all, reveal all" option in the latest updated version of image occlusion

### ISSUE THREAD

**Issue by pseudomonalisa** [glutanimate/image-occlusion-enhanced#103]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS:
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by sindikat** [comment]
The features was removed as per #50 

To emulate this feature, consult the [*changelog*](https://github.com/glutanimate/image-occlusion-enhanced/blob/master/CHANGELOG.md#changes).

**Comment by glutanimate** [comment]
Thanks for chiming in @sindikat. Exactly, Hide all, Reveal All was removed in favor of the options listed in the changelog. However, if you feel like these do not cover your existing use case please feel free to let me know and I will see what I can do.

**Comment by zeguven** [comment]
Hi, I'm new to anki and GitHub! When I use image occlusion, there is no option for hide all, reveal all. How can I add this feature?
