### ISSUE TITLE
_imaging C module ImportError when opening GIF files on Windows or OS X

### ISSUE THREAD

**Issue by Glutanimate** [Glutanimate/image-occlusion-enhanced#11]
Cf. https://anki.tenderapp.com/discussions/add-ons/7506-image-occlusion-2-error

Looks like we're missing a number of precompiled binaries that would be required for GIF support on Windows and OS X (and Linux distros that don't ship with PIL preinstalled).

**Comment by tmbb** [comment]
Maybe this library can help: [https://github.com/shibukawa/imagesize_py]().
It seems to be pure python and contains no binaries.
*Disclaimer*: I've never tried it

**Comment by Glutanimate** [comment]
Oh, that looks interesting! Thanks for the heads-up! I'll definitely give it a try when I find the time.

**Comment by Glutanimate** [comment]
Just pushed a commit to main that implements this library with PIL as a fallback. Thanks again for the suggestion, @tmbb !
