### ISSUE TITLE
Lost the button of "hide all, guess all"

### ISSUE THREAD

**Issue by 514059172** [glutanimate/image-occlusion-enhanced#120]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

why I don't have the button of "hide all, guess all"

![image](https://user-images.githubusercontent.com/45122720/67289998-13af9000-f512-11e9-9bad-758202af5dac.png)

**Comment by BlueGreenMagick** [comment]
https://www.reddit.com/r/Anki/comments/apnac2/hide_all_guess_all_anki_21/

**Comment by glutanimate** [comment]
Thanks for chiming in @BlueGreenMagick !

Just for posterity's sake, here's what I wrote in the linked Reddit thread:

> "Hide All, Reveal All" is no longer available as a mask generation option. With the mask reveal button introduced in recent I/O releases it no longer served much of a purpose and was mostly confusing new users as they expected it to work like a grouped occlusion of all shapes.
> 
> Just in case you were using this option and are now wondering how to cover the same use cases:
> 
> - In case you were using "Hide All, Reveal All" to uncover all labels on the back: Try to switch to using "Hide One, Guess One" coupled with the mask reveal button on the backside (hotkey: G)
> 
> - In case you were using "Hide All, Reveal All" to 'group' your shapes: Use the  [grouping feature](https://github.com/glutanimate/image-occlusion-enhanced/wiki/Advanced-Use#grouping-items) instead
> 
> But I'd be interested to know which use case the option primarily fulfilled for you, and whether or not the alternatives mentioned above satisfy that need (and why).

That last part still applies, BTW: Please do let me know if there is any use case that's not covered by IO's current feature-set, and I'll be happy to reevaluate things.

Closing this issue report for the time being, but feel free to reopen it if you have any thoughts in that regard.
