### ISSUE TITLE
IO Enhanced Anki 2.1 (Alpha) keeps crashing

### ISSUE THREAD

**Issue by starkpsyd** [glutanimate/image-occlusion-enhanced#129]
Hello, every time I fix up the image up I need with the masks how I need them, I'll click to add the cards to the deck and it will gives me this ERROR. I've tried disabling another add-on it said was the likely culprit, but it just keeps giving me this. I don't know what to do... it's getting frustrating :( 

**Error** 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.13 (3ba55990) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.12.6
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Image Occlusion Enhanced for Anki 21 alpha

Caught exception:
  File "aqt/webview.py", line 322, in handler
  File "/Users/adamstark/Library/Application Support/Anki2/addons21/1374772155/add.py", line 278, in <lambda>
    lambda val, choice=choice, close=close: self._onAddNotesButton(choice, close, val))
  File "/Users/adamstark/Library/Application Support/Anki2/addons21/1374772155/add.py", line 293, in _onAddNotesButton
    r = gen.generateNotes()
  File "/Users/adamstark/Library/Application Support/Anki2/addons21/1374772155/ngen.py", line 80, in generateNotes
    (svg_node, layer_node) = self._getMnodesAndSetIds()
  File "/Users/adamstark/Library/Application Support/Anki2/addons21/1374772155/ngen.py", line 190, in _getMnodesAndSetIds
    mask_doc = minidom.parseString(self.new_svg.encode('utf-8'))
<class 'AttributeError'>: 'NoneType' object has no attribute 'encode'

**Comment by starkpsyd** [comment]
Great news, I found the problem. I eventually looked up **glutanimate**'s response to another person with the <class 'AttributeError'>: 'NoneType' object has no attribute 'encode' error over here:
https://anki.tenderapp.com/discussions/add-ons/37537-image-occlusion-enhanced#comment_47647916

I saw it mentioned that non-shape, drawn elements could be the problem, so I deleted the arrow masks I drew on the image and tried again, and IT WORKED!!! 57 cards added! :)

**Comment by glutanimate** [comment]
@starkpsyd glad to hear you managed to get things to work! Hopefully all of these issues will be fixed soon once I find the time to finally fix the masks editor.
