### ISSUE TITLE
Field 1 is empty

### ISSUE THREAD

**Issue by michael-jon** [glutanimate/image-occlusion-enhanced#131]
I really do not understand what I am doing wrong as I have followed multiple tutorials.  I create simple cards with masks, select Hide all, Reveal One.  When I try to add the cards, I keep getting a "Field 1 is empty" and I cannot add the cards to my deck.  My only option is to close but then nothing gets added.  When in the image editor, I am getting cards added but I don't see any additional cards in the deck.  Am I missing something?  Thanks.

**Comment by bigToadMan** [comment]
This one kept getting me too. 

The trick is you don't use the regular Add Cards screen's Add function. There are buttons at the IO screen to Guess One, Show One etc. Hit one and that will Add cards to your deck. Just close the regular Add Cards window when done.

**Comment by michael-jon** [comment]
OMG! Thank you so much!!  It works great.

**Comment by glutanimate** [comment]
Thanks for chiming in @bigToadMan. Yeah, that part of the add-on can be confusing. At some point I should look into adding an in-app message that explains this and directs people to the right flow.
