### ISSUE TITLE
IOE Auto Fit to Canvas Issue

### ISSUE THREAD

**Issue by dsc321123** [glutanimate/image-occlusion-enhanced#132]
Anki 2.1.19 on MacOS Mojave: 

When creating IOE cards, the window interface does not automatically center and resize the image. It does not default to "fit to canvas".

As a workaround, I can click "cmd-f" to have it resize.

![image](https://user-images.githubusercontent.com/48420455/73281546-2515d180-41be-11ea-9165-51ad2455bdf9.png)

**Comment by glutanimate** [comment]
Thanks for the report! Merging this with #92.
