### ISSUE TITLE
Image occlusion enhanced 

### ISSUE THREAD

**Issue by danielzych** [glutanimate/image-occlusion-enhanced#134]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS:
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi Daniel,

It looks like you did not fill out any of the fields of the issue template. Do you still remember what the problem was that you filed the bug report for?

**Comment by glutanimate** [comment]
(closing this issue report for now, but feel free to reopen it once you've added a problem description)

**Comment by danielzych** [comment]
Hi Aristotis,
There was a problem not with image-occlusion-enhanced but with add on
"medical flashcard" during revision it crashed but i deinstalled that and
now everything work. Nevertheless, thank you for your time and response 😊

Have a happy easter 🐰

pon., 13 kwi 2020, 16:38 użytkownik Aristotelis <notifications@github.com>
napisał:
