### ISSUE TITLE
Double masks on Question card

### ISSUE THREAD

**Issue by edwardwel** [glutanimate/image-occlusion-enhanced#142]
Hey, i just got a little bug on my image occlusion enhanced. 
I get double the masks on my question card and the second set is without relation to the picture. Im going to attach an example.
Thanks ! 
![image](https://user-images.githubusercontent.com/63450933/78983166-f6a06500-7b23-11ea-8a59-4690582faf1f.png)

**Comment by glutanimate** [comment]
Hi Edward,

Please see my comment to Jeff here. It should apply to your issue also: https://github.com/glutanimate/image-occlusion-enhanced/issues/144
