### ISSUE TITLE
image occlusion enhanced scroll to answer

### ISSUE THREAD

**Issue by EngAhmed91za** [glutanimate/image-occlusion-enhanced#149]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x ] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### Problem case

i take very long screenshots of books chapters almost 20 pages long, and make alot of boxes for answers i'm trying to go directly to the answer page instead of each time i answer i scroll down

#### Solution

i would like for a feature that allows me to go directly to the spot where the question box is highlighted and when to answer it it remains there.

#### More information

*Additional context: Add any other context or screenshots about the feature request here.*

**Comment by thiswillbeyourgithub** [comment]
Auto scrolling or auto zooming to the box would also be tremendously useful for maps. I made a subway map a while back and it was a pain to have to cut the map in different parts as some station are forever unreadable because they are on the cutting line :/

**Comment by glutanimate** [comment]
Yes, this is something I'd like to add at some point, but it's not easily done since it requires quite fundamental changes to the note type and card template.

Please feel free to track the progress of this request in #82
