### ISSUE TITLE
IOE throwing error, "The first field is empty"

### ISSUE THREAD

**Issue by dwainew** [glutanimate/image-occlusion-enhanced#152]
#### Problem description

Attempts to add IOE cards results in an error dialog stating "The first field is empty." when clicking "Add" button.  The "Add Mode" window does indicate adding cards when HA, GO button is clicked.

I have run through the process with: 

- multiple images, 
- leaving all fields but the image empty,
- all the way to filling in all fields...  
- multiple numbers of masks.
- Hide All, GO and Hide One, GO

I also noticed that going back to the image after a successful close indicates the image wasn't saved.

I started with anki 2.1.22, but upgraded to 2.1.26.  All other add-ons seem to be working.

![image](https://user-images.githubusercontent.com/6252957/83278022-c66e5d80-a187-11ea-87f6-b2f3c4c99358.png)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X ] I've restarted Anki to see if it helps
 - [X ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ X] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [X ] I've tried to disable other add-ons to see if there are any interactions present
 - [? can't repo in this case] My issue disappears when I hold shift while starting Anki.
 - [X ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-05-28 13:57:29
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Advanced Browser ['874215009', 2020-02-20T14:39, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T19:21, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Enhance main window ['877182321', 2020-05-03T09:58, 'None', '']
    HTML Editor Tweaks v02 ['410936778', 2020-03-22T06:58, 'None', '']
    Heatmap ['1722241614', 2019-08-18T08:35, 'None', '']
    Hierarchical Tags 2 ['594329229', 2020-04-11T09:36, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-03-23T10:32, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T02:11, 'None', '']

```

#####  If you are using Anki 2.0

*__ONLY IF YOU ARE USING ANKI 2.0__: Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS: Win 10 
- version: build 1909

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

![image](https://user-images.githubusercontent.com/6252957/83279123-785a5980-a189-11ea-92fc-a0d200a1daa4.png)

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
![image](https://user-images.githubusercontent.com/6252957/83280181-1f8bc080-a18b-11ea-9f4f-20d9210e4c1e.png)

```

**Comment by dwainew** [comment]
I just realized that after attempting to add cards to build this issue that at least some of the attempts actually succeeded, despite the error!  I did notice that every once in awhile, clicking close did not give the "data will be lost" warning dialog.  But I do get the empty field error whenever I click Add.

**Comment by rnwolf** [comment]
I get the same error.

```
    Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-06-01 09:44:11
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2020-04-03T17:06, 'None', '']
    Enhance main window ['877182321', 2020-05-03T17:58, 'None', '']
    Frozen Fields ['516643804', 2020-03-01T04:12, 'None', '']
    Image Occlusion Enhanced ['image_occlusion_enhanced', 2020-04-28T18:45, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-03-23T17:32, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T14:23, 'None', '']
    Speedfocus (auto good and pause) ['Speedfocus', 0, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    153625306 318752047 516643804 877182321
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T10:11, 'None', '']
```

**Comment by glutanimate** [comment]
Hi there,

Thanks for taking the time to file a report, and adding all the debug info. I really appreciate that!

However, I'll have to refer you to the tutorials on YouTube, etc. (e.g. https://youtu.be/hyU2W7VgBmw?t=139): There is no need to click on the "Add" button in Anki's regular "Add Cards" window. Everything is handled inside the Image Occlusion Enhanced window. Once you click on one of the "Add Cards" buttons in that window, the notes will be added (as confirmed by notification).

Though I realize that this is a bit confusing, and reworking the UX in that department is on my todo list.
