### ISSUE TITLE
‘Esc’ key’s accidental press leads to whole work being discarded.

### ISSUE THREAD

**Issue by himanshubabal** [glutanimate/image-occlusion-enhanced#153]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### Problem case

Accidental press of **Escape** key leads to the whole window being dismissed without any warning.

#### Solution

I would love if you could change the shortcut from `Esc` to something else, or maybe throw a message before closing the IOE window.

#### More information

I really appreciate all the hard work you put in and wanted to thank you for it.

**Comment by glutanimate** [comment]
Thanks for the kind words, and for taking the time to submit this suggestion! This should hopefully land in the next feature release (thanks to a patch submitted by 5hir0kur0). You can track the progress of that here: #72 .
