### ISSUE TITLE
Option for additional user-defined fields (e.g. to support Note ID add-on)

### ISSUE THREAD

**Issue by Rektis** [Glutanimate/image-occlusion-enhanced#16]
Is it possible to **support the Note ID add-on?**

The Note ID add-on can be found [here](https://ankiweb.net/shared/info/1672832404).
Code: 1672832404

Image Occlusion 2 Enhanced really screws up the order of my Anki library, because everything except its notes is sorted by the "Note ID" field.

I also really feel limited by not being able to add fields, because I also have a field specifying the date a note was made everywhere ("Timestamp"), but I refrain from doing that for the IO2/E note type because the "Don'ts" say not to add fields.
**Would it really be so bad to add some fields?** I'd want to have more flexibility there.

**Comment by Glutanimate** [comment]
The way Anki currently works you can only have one of the following:

- either a predefined number of fields that can be freely renamed, but not rearranged
- or a customizable number of fields that can be freely rearranged, but not renamed

Image Occlusion has always used the first option for its note type. The reasons for this are threefold:

1. Switching to the second option would require a lot of work and open a Pandora's box in terms of backwards-compatibility issues
2. Lots of users like to rename their fields, e.g. to adapt them to their locale
3. There are three additional fields defined in the note type (TempField3-5) that users are more or less free to use for whatever purpose they wish, which should somewhat alleviate the fact that you can't add any fields

So in your case I would just rename *TempField4* to *Note ID* and *TempField5* to *Timestamp*. Though there still is a limitation with this solution in that you can only edit these fields from the card browser (they don't appear in the Image Occlusion "Add note" dialog).

**Comment by Rektis** [comment]
Aren't you keeping those temporary fields around in case you want to add new functions?

If I used them for mine, wouldn't I run into compatibility issues by filling the fields with information later on? Then again, should you use those for new functions, I can just batch copy the information to a new field.

How about adding an optional way to show the temporary fields in the Image Occlusion "Add note" dialogue?

**Comment by Glutanimate** [comment]
> Aren't you keeping those temporary fields around in case you want to add new functions?

Yes, that was the plan initially. I don't see the project needing these fields anytime soon, though. Maybe one field at most (that's why I'd recommend skipping TempField3).

> If I used them for mine, wouldn't I run into compatibility issues, by filling the fields with information, later on?

Possibly, but if the add-on ever starts making use of these fields I'll point this out explicitly in the changelog.

> Then again, should you use those for new functions, I can just batch copy the information to a new field.

If I ever have to use all three I'll likely add one or two extra fields that will be free to assign to whatever you wish, so yes.

> How about adding an optional way to show the temporary fields in the Image Occlusion "Add note" dialogue?

This is not a bad idea, but I simply don't have the time to implement this right now.  With the [Anki 2.1.0 release](https://anki.tenderapp.com/discussions/beta-testing/172-anki-210-alpha-1/page/1) drawing closer, IO will soon have to be ported to Qt5 and python3. Any new features will have to wait at least until that is done.

**Comment by Glutanimate** [comment]
Hi,

the latest dev release of the add-on now comes with a new note type that supports an arbitrary number of user-defined fields. These will appear in the Editor window, too. I have also implemented Note ID field, albeit not in the same way as Note ID add-on. In addition to preventing Anki from marking notes as duplicates, the ID now serves as a unique identifier that is core for the new note editing features introduced in the latest release.

As for the TempFields, they have been removed on favor of two new fields called "Extra 1" and "Extra 2". If you've used the former before you can just transfer your data to the new fields when changing the note type. (Of course you don't have to change the note type on your existing notes to keep reviewing them, but it might come in handy if you ever want to edit your notes).

The new update isn't out, yet, but I will soon be creating a beta [release](https://github.com/Glutanimate/image-occlusion-enhanced/releases). Feel free to give it a try if you want.

For now I am marking this issue as closed.
