### ISSUE TITLE
The front of this card is blank

### ISSUE THREAD

**Issue by Sete96** [glutanimate/image-occlusion-enhanced#164]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
While i create new IOE cards everythings seems pretty normal, but when i try to review one the front appears to be blank. i have confirmed that all fields are filled with something(header, image, question mark, etc).  I don't know what's happening, but it makes me sad. Thanks in advance and keep the great work!1

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.29 (bbff62bf) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-08-04 21:33:41
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T22:21, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T09:23, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
The front of this card is blank. More information
![image](https://user-images.githubusercontent.com/69227140/89363690-c8c8c880-d69e-11ea-8f24-f36a3aa5ed6f.png)

```

**Comment by SyntagmaX** [comment]
I have the same problem.
