### ISSUE TITLE
Image Occlusion shows answer first then image with occlusions

### ISSUE THREAD

**Issue by pstale2** [glutanimate/image-occlusion-enhanced#169]
Problem description

I downloaded the Image Occlusion add-on. Then, I had some issues with configuration due to deleting some of the fields accidentally. Finally got that to work. Now, when I occlude an image and it adds the cards, the answer (image with no occlusions) is the question. The answer is the occluded image.

#### Checklist

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.30 (06a69c25) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=False sv=1
    Add-ons, last update check: 2020-08-13 22:02:30
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-27T21:21, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1374772155
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

```

#### Error message (if any)

When I tried to flip the cards, it says, "Anki couldn't find the line between the question and answer. Please adjust the template manually to switch the question and answer."

```python

```
front template says:
{{#Image}}
<div id="io-header"></div>
<div id="io-wrapper">
  <div id="io-overlay"></div>
  <div id="io-original">{{Image}}</div>
</div>
<div id="io-footer"></div>

<script>
// Prevent original image from loading before mask
aFade = 50, qFade = 0;
var mask = document.querySelector('#io-overlay>img');
function loaded() {
    var original = document.querySelector('#io-original');
    original.style.visibility = "visible";
}
if (mask === null || mask.complete) {
    loaded();
} else {
    mask.addEventListener('load', loaded);
}
</script>
{{/Image}}

back template: 
{{#Image}}
<div id="io-header"></div>
<div id="io-wrapper">
  <div id="io-overlay">{{Answer Mask}}</div>
  <div id="io-original">{{Image}}</div>
</div>
<div id="io-footer"></div>
<button id="io-revl-btn" onclick="toggle();">Toggle Masks</button>
<div id="io-extra-wrapper">
  <div id="io-extra">
    
      <div class="io-extra-entry">
        <div class="io-field-descr">Remarks</div>
      </div>
    
    
      <div class="io-extra-entry">
        <div class="io-field-descr">Sources</div>
      </div>
    
    
      <div class="io-extra-entry">
        <div class="io-field-descr">Extra 1</div>
      </div>
    
    
      <div class="io-extra-entry">
        <div class="io-field-descr">Extra 2</div>
      </div>
    
  </div>
</div>

<script>
// Toggle answer mask on clicking the image
var toggle = function() {
  var amask = document.getElementById('io-overlay');
  if (amask.style.display === 'block' || amask.style.display === '')
    amask.style.display = 'none';
  else
    amask.style.display = 'block'
}

// Prevent original image from loading before mask
aFade = 50, qFade = 0;
var mask = document.querySelector('#io-overlay>img');
function loaded() {
    var original = document.querySelector('#io-original');
    original.style.visibility = "visible";
}
if (mask === null || mask.complete) {
    loaded();
} else {
    mask.addEventListener('load', loaded);
}
</script>
{{/Image}}

**Comment by glutanimate** [comment]
Hi there,

Please see my answer here: https://forums.ankiweb.net/t/image-occlusion-shows-answer-first-then-image-with-occlusions/2284
