### ISSUE TITLE
SVG files are not displayed

### ISSUE THREAD

**Issue by hoangtrongtienuk** [glutanimate/image-occlusion-enhanced#181]
#### Problem description

This is my first time using this add-on
After adding rectangles hiding relevant information, I clicked "hide all, reveal one"; however, the cards don't appear to be able to add images. Images in questions and answer original fields seem to be broken. SVG files cannot be shown. I tried both the latest version of Anki and version 2.1.24 but the problem persists

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.34 (8af8f565) Python 3.8.0 Qt 5.15.1 PyQt 5.15.1
    Platform: Windows 10
    Flags: frz=True ao=False sv=1
    Add-ons, last update check: 2020-09-30 20:55:57
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Additional Card Fields Fork for 21 ['744725736', 2020-09-20T18:50, 'None', mod]
    AnkiConnect ['2055492159', 2020-07-13T02:54, 'None', '']
    Card Info During Review ['2179254157', 2020-07-09T07:06, 'None', '']
    Deck Stats ['1421528223', 2020-09-03T02:45, 'None', '']
    Edit Field During Review ['1020366288', 2020-09-23T01:38, 'None', '']
    Fast Word Query Multi-threaded queries for words from local or web dictionaries ['1807206748', 2019-06-23T10:10, 'None', '']
    Frozen Fields ['516643804', 2020-03-01T11:12, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T09:21, 'None', '']
    Mini Format Pack ['295889520', 2018-07-25T00:45, 'None', '']
    Replay buttons on card ['498789867', 2017-11-20T19:38, 'None', '']
    Reset Card Scheduling ['300884351', 2018-09-18T23:17, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T20:23, 'None', '']
    Syntax Highlighting for Code ['1463041493', 2018-10-07T08:31, 'None', '']
    load balancer ['1417170896', 2020-08-06T06:58, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1020366288 1374772155 1417170896 1421528223 1463041493 1807206748 2055492159 2179254157 295889520 300884351 498789867 516643804 744725736
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Show duplicates ['865767531', 2020-02-03T14:41, 'None', '']

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```
I would like to include image of a note and a card relating to the error
![image](https://user-images.githubusercontent.com/30747842/94801835-d38aaa00-0410-11eb-8822-019e315f61c9.png)
![image](https://user-images.githubusercontent.com/30747842/94801847-d7b6c780-0410-11eb-9c27-d1ec9da42e13.png)

**Comment by hoangtrongtienuk** [comment]
I would like to include image of a note and a card relating to the error
![image](https://user-images.githubusercontent.com/30747842/94801654-8e667800-0410-11eb-9eab-979736bff105.png)
![image](https://user-images.githubusercontent.com/30747842/94801682-99b9a380-0410-11eb-921a-566d2e450e77.png)

**Comment by gravidarum** [comment]
hello,
i have the same issue 
[https://github.com/glutanimate/image-occlusion-enhanced/issues/321](https://github.com/glutanimate/image-occlusion-enhanced/issues/321)
How did u solve it please?
