### ISSUE TITLE
Can't set img {max-height: 875px;} without affecting front and back

### ISSUE THREAD

**Issue by pchernof** [Glutanimate/image-occlusion-enhanced#19]
I want to set img {max-height: 875px;} but only on the back of the card so that I can add some text in "Remarks" and have a smaller image *only* if the image is so large that the text would appear off-screen. Please help!

**Comment by Glutanimate** [comment]
Try adding a class to the back template that marks it as the back of the card, e.g.:

    <div id="io-wrapper" class="backside">
      <div id="io-overlay">{{Answer}}</div>
      <div id="io-original">{{Original Image}}</div>
    </div>

Then you should be able to select all img elements on the back with:

    img .backside{
      max-height: 875px;
    }

However, as this is more of a general card styling question than an actual problem with the add-on I will mark this issue as closed. It's fine that you posted it here, but in the future please use the [support thread](https://anki.tenderapp.com/discussions/add-ons/8295-image-occlusion-enhanced-official-thread) on the Anki forums for questions like this.

**Comment by pchernof** [comment]
You are a merciful god
