### ISSUE TITLE
Switch to note type based on cloze deletions if possible

### ISSUE THREAD

**Issue by Glutanimate** [Glutanimate/image-occlusion-enhanced#2]
No idea if this is feasible, but it would make it much easier to revise notes after they've been created. Right now we have to edit each of the several notes generated by one image occlusion separately.

**Comment by tmbb** [comment]
Don't do it... It's a minefield. An old version of IO2 worked using clozes and uncovered all kinds of weird CSS bugs and annoyances for vert little gain

**Comment by Glutanimate** [comment]
Huh, thanks for letting me know! I'll stay away from this for now.

**Comment by Glutanimate** [comment]
Marking this as closed, as I don't see any need for this any more.
