### ISSUE TITLE
The asian texts are garbled when I "RE-EDIT" the card.

### ISSUE THREAD

**Issue by jemonaff** [Glutanimate/image-occlusion-enhanced#23]
Hi, thank you for very useful add-on IOE.
I'm not good at english, so im going to explain about my issue by images.
please see the link.
http://i.imgur.com/sv5oy6a.png
Could you update IOE for this?
or is it a SVG Edit Issue?

thank you for reading this.
Win7 64bit JPN / Anki 2.0.36 /IOC Updated 2016-12-03

**Comment by Glutanimate** [comment]
Hi jemonaff,

thanks for the detailed report and taking the time to compile that demonstration. Made it much easier to track this issue down!

I think I've found a way to fix this. Could you please give the [latest beta release](https://github.com/Glutanimate/image-occlusion-enhanced/releases/tag/v1.0.4-beta) a try and let me know if everything works fine for you? If you don't know how to install it, the instructions are available [here](https://github.com/Glutanimate/image-occlusion-enhanced/wiki/Installation#manual-installation).

**Comment by jemonaff** [comment]
Thank you, Glutanimate.
The font problem is totally fixed!
http://i.imgur.com/WxfBboD.png
Thank you very much!

**Comment by Glutanimate** [comment]
Glad to hear that! I'll push a stable release with the fix out soon.
