### ISSUE TITLE
cards wont add

### ISSUE THREAD

**Issue by fciftci06** [glutanimate/image-occlusion-enhanced#26]
Every time i create notes with image occlusion it says the notes were added on the bottom left side but the cards are not added to the deck. They're not added to another deck either or I just can't seem to find them

**Comment by Glutanimate** [comment]
Try adding a few cards, then go to the browser and see if they appear when you click on "Added Today" (make sure it only says `added:1` in the search bar). If they do appear there they might have been added to the default deck. In that case make sure to select a different deck when adding the cards (the deck selection button is on the fields tab in the IO Editor).

If the cards don't appear in the browser with that search phrase there is likely a bug at play and we'll have to investigate this further.

**Comment by glutanimate** [comment]
Closing this as it seems like it's resolved.
