### ISSUE TITLE
SVG images are offset

### ISSUE THREAD

**Issue by ShadyMedic** [glutanimate/image-occlusion-enhanced#268]
#### Problem description

Using a SVG image as the one to cover with rectangles offsets them.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README. **No, because I can't search for that easily – I type in SVG and I get too many results about issues related to SVG-edit.**
 

#### Information about your Anki set-up

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```
    
    Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2022-11-02 17:21:14
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Countdown To Events and Exams ['1143540799', 2022-06-27T13:50, 'None', '']
    Customize Keyboard Shortcuts ['24411424', 2022-09-14T11:12, 'None', mod]
    Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']
    Progress Bar original ['1685464019', 2022-07-28T07:24, 'None', mod]
    Quizlet to Anki 21 Importer with audio support ['1362209126', 2022-10-30T19:46, 'None', '']
    The KING of Button Add-ons ['374005964', 2020-04-18T00:33, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1143540799 1362209126 1374772155 1685464019 24411424 374005964
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Improved Quizlet to Anki 21 Importer ['538351043', 2020-11-15T03:16, 'None', '']
    Progress Bar cards done cards left secondscard time spentleft and ETA ['1097423555', 2022-08-05T13:01, 'None', '']

```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python
No error
```

**Comment by ShadyMedic** [comment]
Also I'll add an image once my internet works again.

**Comment by ShadyMedic** [comment]
Here are the images

When creating the cards:
![image](https://user-images.githubusercontent.com/19894267/199549750-69ee8d37-e2d8-404c-910b-b416c20812d5.png)


When reviewing the cards:
![image](https://user-images.githubusercontent.com/19894267/199549903-3de22eb1-73b3-4ecd-9ead-c40f50a0280b.png)

**Comment by glutanimate** [comment]
Hi there, thanks for the report. Sounds like a potential template issue, which case this post should help: https://forums.ankiweb.net/t/image-occulsion-keeps-hiding-other-places-than-where-i-intended/23995/2

**Comment by glutanimate** [comment]
(if this doesn't help, let me know, and I'll reopen the issue / troubleshoot further)

**Comment by ShadyMedic** [comment]
Hey there, thanks for answering.

Unfortunatelly, that posted didn't resolve the issue.

I found out something interesting though. If I decrease the window width to a certain point, the positioning fixes itself. The problem is, that I'm making the deck mostly for my classmates and they need it to work on all their devices.
![image](https://user-images.githubusercontent.com/19894267/199557063-ab1e08cb-c8d0-4887-bda8-5c0c72ba948e.png)

![image](https://user-images.githubusercontent.com/19894267/199556943-41a0d0c5-cb8e-4a07-8689-5a8d69612680.png)

Also, this issue doesn't occur when converting those SVG images into PNG and using those as a base. The quality is bad though.

**Comment by ShadyMedic** [comment]
> (if this doesn't help, let me know, and I'll reopen the issue / troubleshoot further)

Uh... hey, so just reminding you, that the issue isn't resolved yet.
