### ISSUE TITLE
Toggle Masks Button doesn't work

### ISSUE THREAD

**Issue by quangkhuedinhdo** [glutanimate/image-occlusion-enhanced#29]
I recently installed Image Occulusion Enhanced. Almost things work perfectly.

But I noticed that the Toggle Masks Button didn't work on PC and Android.

For more informations:
- I just fill out one field with text and sound, not all. Exactly I fill out the the field Extra 1.
- I modified Extra 1 field css (class: io-extra-entry): display: none;
Here is screenshot of Edit Mode of mine:

![image](https://cloud.githubusercontent.com/assets/18014311/24623618/3b5a37b8-18d3-11e7-960b-f66d4f971f52.png)

**Comment by glutanimate** [comment]
Hi @quangkhuedinhdo,

please try [restoring the default card templates](https://github.com/glutanimate/image-occlusion-enhanced/wiki/Troubleshooting#card-template) and see if the button works after that.

**Comment by quangkhuedinhdo** [comment]
@glutanimate 

Yup, I recently tried all of the restoring things you mentioned, but the button doesn't work at all. :(

**Comment by glutanimate** [comment]
ok, I see. Just so we're clear: The button does appear, but it won't toggle your masks when clicking on it? 

Also: You're using the "Hide All, Reveal One" mode, right? (that's the only mode the button works with as the other ones don't have masks to toggle on the answer side)

**Comment by quangkhuedinhdo** [comment]
OMG. I used "Hide One, Review All". I just think the button to use for all, and I can switch to see or not see the masks whenever I want. Sorry for taking your time because of my silly thing :|. And thanks for your fast replying :smile:

**Comment by glutanimate** [comment]
Glad to hear it works. No problem, these things happen :). I think I'll just have to make it clearer in the documentation that the button only works when there are masks visible on the answer side.
