### ISSUE TITLE
Fix SVG question mask attribute

### ISSUE THREAD

**Issue by frichter** [glutanimate/image-occlusion-enhanced#30]
After the most recent iOS update, the question portion is displayed on my desktop but not my iPhone (screenshots below). The card in the screenshots below was originally Image Occlusion 2.0. I converted it to [Image Occlusion Enhanced note type IO Card successfully](https://github.com/Glutanimate/image-occlusion-enhanced/wiki/Upgrading), but the issue still persisted. 

This issue seems to have previously occurred on AnkiDroid in 2015: [google group discussion 1](https://groups.google.com/forum/#!topic/anki-android/0956yETPFc0), [google group discussion 2](https://groups.google.com/forum/#!topic/anki-android/yDdzd1hh46k), [github image-occlusion-2 bug report](https://github.com/tmbb/image-occlusion-2/pull/12), [ankidroid FAQ reference](https://github.com/ankidroid/Anki-Android/wiki/FAQ#after-updating-my-android-version-image-occlusion-is-no-longer-working), and [the github solution](https://github.com/mrestko/image-occlusion-svg-fix).

After implementing the AnkiDroid solution for this single card the issue was fixed. Not sure if this is the appropriate forum where this issue should be posted.

Computer (MacOS Sierra 10.12.4):

![image](https://cloud.githubusercontent.com/assets/5546938/25073474/af71a762-22b5-11e7-835c-1d0e372ccedc.png)

Mobile app (iPhone 6s Plus iOS 10.3.1):

![image](https://cloud.githubusercontent.com/assets/5546938/25073493/fa43458e-22b5-11e7-8ea0-65e59fa93f1c.png)

UNFIXED question svg in collection.media folder:
![image](https://cloud.githubusercontent.com/assets/5546938/25073734/8d76c48a-22ba-11e7-8117-2168328f385a.png)

FIXED question svg in collection.media folder:
![image](https://cloud.githubusercontent.com/assets/5546938/25074223/53b01aee-22c4-11e7-88f4-55a302ef6825.png)

**Comment by frichter** [comment]
After running the python fix on all the files, I can't seem to get my collections.media to update on AnkiWeb! I tried [adding and removing media](https://apps.ankiweb.net/docs/manual.html#media), "Check Database", and "Check Media". Any suggestions? Again not sure if this is the appropriate forum, but any redirection would be much appreciated

**Comment by frichter** [comment]
In order to have the changes take effect [files have to be added or deleted](https://apps.ankiweb.net/docs/manual.html#media).

**Comment by glutanimate** [comment]
Thanks for letting me know, @frichter. I've added a note on the issue to the add-on description. I would like to investigate getting the repair tool integrated into the add-on at some point, but due to lack of time I'm afraid that a link to the fix will have to suffice for now.

**Comment by glutanimate** [comment]
I've just implemented the repair script as a small [add-on](https://ankiweb.net/shared/info/1048682320). That should hopefully make it easier to solve this issues for users that aren't as familiar with the command-line (especially on macOS).

I don't think there's much more we can do at this point, so I'm marking this issue as resolved.
