### ISSUE TITLE
Add support for Anki 2.1+

### ISSUE THREAD

**Issue by xandep** [glutanimate/image-occlusion-enhanced#32]
As I didn't see any mention on the wiki about IO support on Anki 2.1, so I tried it anyway. It doesn't work, it seems. It says on Anki page that adding support on add-ons should not be too cumbersome, so it might be a interesting future update.

**Comment by jkl1337** [comment]
What are your thoughts on one codebase with backward compatibility, eg using https://github.com/mottosso/Qt.py?

**Comment by glutanimate** [comment]
I'm not familiar with Qt.py, but backward compatibility would certainly be a major advantage – especially in that transitory period where a lot of users will want to stay with Anki 2.0.x due to add-ons that might not have been updated, yet. But I'm afraid that any work on this from my part will have to wait until late summer.

**Comment by xandep** [comment]
Just an opinion, but IO is in pretty good shape right now (been using it a lot). I see no problem in halting development, keeping it compatible with Anki 2.0 as it is, and then focusing on the new branch with 2.1 compatibility. As soon as 2.1 is stable there will be no reason to use Anki 2.0 besides compatibility with old addons, and for it there will still be "the old" (or as of now, the current) IO.

**Comment by glutanimate** [comment]
I think it's too early to tell. 2.1 still has long ways to go. It's too unstable in its current stage to be developing against. The main issue I see is that most of the problems seem to be stemming from Qt5 itself, meaning that we will probably have to wait for new iterations of the toolkit to fix the corresponding bugs in Anki 2.1. I don't think we will see a stable release of Anki 2.1 for a while and developing 2.1 support before that would probably be a waste of time.

I think you're also underestimating the staying power of Anki 2.0.x. Most users probably won't switch until a major feature update. With an add-on environment as rich as that of Anki it might be months before 2.0.x and 2.1 have reached feature parity in terms of add-on support. That will keep users glued to Anki 2.0.x for a long time.

**Comment by donfed** [comment]
Any updates for this? Is the 2.1 development branch safe to load on my anki profile and can you add new cards? I don't have a technical background so sorry I can't help but the only addon I am missing for 2.1 is this one. Thanks for all the hard work you have put into these glutanimate!

**Comment by glutanimate** [comment]
The 2.1 branch seems to be working fine so far, but I haven't had the chance to perform any extensive tests, yet. This is why I would advise against using it for now. My spring study break is about to start, so I should be able to get back to working on this very soon. Once I've done some more tests I will release a separate 2.1 beta version on AnkiWeb and notify you here.

Appreciate the kind words!

**Comment by xandep** [comment]
I'm thrilled to hear that! You can bet Anki & IO enabled MANY success
stories already (soon to incude mine ;-) )

Alexandre Pesca

2018-02-05 13:46 GMT-02:00 Aristotelis <notifications@github.com>:

**Comment by glutanimate** [comment]
Hey everyone,

Anki 2.1 support for Image Occlusion Enhanced is finally here! I would appreciate it if you could help me test it: https://ankiweb.net/shared/info/1374772155

Feel free to report any bugs or regressions you encounter as new issues here on GitHub. For general feedback and suggestions you can also use the official support thread on the Anki forums: https://anki.tenderapp.com/discussions/add-ons/8295-image-occlusion-enhanced-official-thread

**Comment by xandep** [comment]
YES! I literally checked just yesterday! This is wonderful news.

Em sex, 29 de jun de 2018 21:02, Aristotelis <notifications@github.com>
escreveu:
