### ISSUE TITLE
Right click on any image inside a card to make an IOE from it.

### ISSUE THREAD

**Issue by JulyMorning** [glutanimate/image-occlusion-enhanced#35]
The only one default method is to copy it. It would be great to have an ability to make a IOE card as simple like this, through the right click. It would be also great to have an ability to see if the current image is already a part of some IOE card to modify it.

**Comment by glutanimate** [comment]
Thanks for the feature request. This has actually been available in the master branch for a while now (8c50e1d2ab19571e45ec081c19e148977aabe2e2) and will be part of the next major release of IO Enhanced.

As far as handling existing IO notes based on that image is concerned: There might be some instances where creating multiple independent occlusion sets from one image is necessary. For that reason it's important to always have the ability to create new cards from an image, even if it has been used for IO already.

Of course it would be possible to just add an additional entry to the context menu upon detecting that an image as been used in IO previously; but I'd like to keep the context menu simple for now, especially with Anki 2.1 looming ahead in the not-too-distant future.
