### ISSUE TITLE
Ablilty to bind the cards.

### ISSUE THREAD

**Issue by JulyMorning** [glutanimate/image-occlusion-enhanced#36]
It would be great, if we could not only group the fields to display together («G» hotkey), but to exclude some of them to display in one session. Basically, it means that they should be made as one note with two cards/sides. It should fit for some images with a list of [key, value] entries. helping to exclude a value when a key was already shown or planned to be shown.

**Comment by glutanimate** [comment]
Hi July,

this would be a nice addition, but I'm afraid that linking together multiple unconnected notes is not possible in Anki right now. [There was some discussion at some point to switch to a new note type based on cloze deletions](https://github.com/glutanimate/image-occlusion-enhanced/issues/2), but it wouldn't have worked properly and so I've set it aside, pending improvements to Anki's note type system.

For now I'd recommend that you manually suspend and unsuspend the respective cards as needed.
