### ISSUE TITLE
Creation of "Blank" Cards

### ISSUE THREAD

**Issue by hellhound-omega** [glutanimate/image-occlusion-enhanced#40]
This is an issue that has come up recently for me and I lack a better descriptor than "blank."

Essentially, the addon seems to double or triple the amount of cards made from a single image in which none of the masks are highlight or revealed. For example, if I were working on an anatomical image and had 6 labels covered, the addon would generate 12 cards, 6 of which would be non-functional as no masks would be selected or revealed on the back.

I do not get an error message from this, but I am unsure why this started occurring. I tried uninstalling and uninstalling the addon, but it doesn't seem to change anything.

UPDATE: I just tested it out. It seems to be an issue with using my stylus. I have a Surface Book and when I create the boxes with my Surface Pen it creates the problem described above. However, this did not use to happen.

**Comment by glutanimate** [comment]
Thanks for the detailed report! Touchscreen support for SVG-Edit (the component IO uses for drawing shapes) is sadly very lacking and so its riddled with bugs like these.

I did include a workaround the master branch (https://github.com/glutanimate/image-occlusion-enhanced/commit/064f5dc153a02ce959ca8b60d852f9234f8ccfe6) that should be included in the next release (ETA in a month or so).

My recommendation until then is to keep using a mouse to draw your shapes.
