### ISSUE TITLE
Naming the masks

### ISSUE THREAD

**Issue by ETHkessler** [glutanimate/image-occlusion-enhanced#41]
Is it somehow possible to edit the Image so that you can put a info on the mask itself which will be displayed in another color and dissapers when you press "answer" ? I tried it and just grouped it with the mask but since the color of the text and the mask is the same it doesn't work that way:

Thanks Thomas

![bsp](https://user-images.githubusercontent.com/33898661/33127065-377e9858-cf87-11e7-82cd-1f4421e05b7e.png)

**Comment by glutanimate** [comment]
Thanks for the suggestion, Thomas!

Incidentally [this is already implemented](https://github.com/glutanimate/image-occlusion-enhanced/commit/c904a574f0f5ef4bc424328e332245884fee2711) in the current master branch (alongside a lot of other fixes and improvements). I just have to find the time to do some more testing before I can publish a new release.

FWIW, you could [install the current master branch manually](https://github.com/glutanimate/image-occlusion-enhanced/wiki/Installation#manual-installation) if you'd like, but I'd highly recommend giving it a try on a spare Anki profile / config directory first. I have been using the master branch for a few months now, but I can't guarantee that there aren't any platform-specific bugs or other hidden issues that I've missed.

**Comment by glutanimate** [comment]
@ETHkessler regarding your comment on the commit (the first link):

While you could apply the change manually, what I meant to say was that you should rather give the current development release of the add-on a try (the master branch). In order to do so you will have to download [this zip](https://github.com/glutanimate/image-occlusion-enhanced/archive/master.zip) and then follow the instructions [here](https://github.com/glutanimate/image-occlusion-enhanced/wiki/Installation#manual-installation) starting from step 2.

Though, as I said above, using a development release is potentially dangerous. So you should use a spare Anki profile to test the add-on first.

**Comment by ETHkessler** [comment]
Hey Glutanimate

Thanks for the fast answer, I have already installed the current master branch and I have no Problems with it so far but regarding the labeling of the mask I couldn’t figure out how it should work thanks for your time. 



Gesendet von Mail für Windows 10

Von: Aristotelis
Gesendet: Donnerstag, 7. Dezember 2017 21:10
An: glutanimate/image-occlusion-enhanced
Cc: ETHkessler; Mention
Betreff: Re: [glutanimate/image-occlusion-enhanced] Naming the masks (#41)

@ETHkessler regarding your comment on the commit (the first link):
While you could apply the change manually, what I meant to say was that you should rather give the current development release of the add-on a try (the master branch). In order to do so you will have to download this zip and then follow the instructions here starting from step 2.
Though, as I said above, using a development release is potentially dangerous. So you should use a spare Anki profile to test the add-on first.

**Comment by glutanimate** [comment]
Oh, I see. Ok, so you basically just have to draw your shape and text label, and then just group them. In the master branch the label should retain it's color instead of being colored the same as the question shape it's attached to.
