### ISSUE TITLE
Automatically fit new image to canvas after changing it from the IO Editor

### ISSUE THREAD

**Issue by nomdeplume123** [glutanimate/image-occlusion-enhanced#42]
When I click on "add" the addon often incorrectly assumes that I want to place the last screenshot so it puts it on the screen at "zoom to fit canvas."  Then when I click on "change image" and choose the image I want to place, it places that image but DOES NOT correctly place it at "zoom to fit canvas."  instead the image is kept at the same zoom as the previous image, so I have to manually click on "zoom to fit canvas."  It would be better if the program automatically zoomed to fit canvas when changing from one image to another.

**Comment by glutanimate** [comment]
Thanks for the suggestion. [I actually tried to implement that back in the day](https://github.com/glutanimate/image-occlusion-enhanced/blob/master/image_occlusion_enhanced/add.py#L252), but for the some reason the image would not be positioned correctly. I might give this another try in the future. It would definitely be much neater if the add-on adjusted the canvas automatically.

**Comment by glutanimate** [comment]
Thanks again for the suggestion, @nomdeplume123! This feature is now implemented in the development branch and will be available in the first stable Anki 2.1 release of Image Occlusion Enhanced.
