### ISSUE TITLE
 Add-on Commission

### ISSUE THREAD

**Issue by GitHub01945** [glutanimate/image-occlusion-enhanced#44]
Hello Glutanimate, 

Do you still accept commission requests for anki add-ons?

(Sorry. It seems github doesn't allow direct messages.)

**Comment by glutanimate** [comment]
Hi there!

Sure! Just drop me a message at ankiglutanimate[αt]gmail.com so we can discuss the details. (I do have a couple of commissions I need to work on first, but I'll try to get to your request as soon as I can.)

**Comment by GitHub01945** [comment]
Okay, thanks! I just sent you an e-mail.
