### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by brettz9** [glutanimate/image-occlusion-enhanced#70]
Neat application!

I intend to take a closer look at your svgedit issue shortly, but just wanted to make a quick observation that you are missing the license file that is expected per the GPL Affero license: https://www.gnu.org/licenses/gpl-howto.html#content . Adding it also has the bonus that Github should auto-link to the license for you...

(And FWIW, since it is a JS application, you might also be interested in https://www.gnu.org/licenses/javascript-labels.html though this is not required...)

**Comment by glutanimate** [comment]
Thanks a lot for taking the time to report this, Brett! I thought I had added a license, but it turns out I only did for the current development branch. So I really appreciate the reminder!

Thanks also for the note on the license web labels. I'll make sure to check that out!
