### ISSUE TITLE
Feature/Add-on request: distinct visual cues for cloze deletion notes with multiple cards

### ISSUE THREAD

**Issue by sproodl** [glutanimate/image-occlusion-enhanced#78]
Feature: When generating multiple cards from a single cloze deletion note I'd love to add distinct visual cues for each card.

Illustration:
imagined code like "My favorite colors are {{visualcloze1::green;image}}, {{visualcloze2::blue;image}} and {{visualcloze3::red;image}}", imagined cards like:
1. front "My favorite colors are {{visualcloze1::green}}, blue and red" + an image that works as a visual cue for "green"
2. front  "My favorite colors are green, {{visualcloze2::blue}} and red" + an image that works as a visual cue for "blue"
3. front  "My favorite colors are green, blue and {{visualcloze3::red}}" + an image that works as a visual cue for "red"

I only managed to show the same image for all cards generated from one note. At the moment to achieve the desired outcome I'd have to make three seperate notes which I find less effective.

**Comment by glutanimate** [comment]
Thanks for the feedback. I just posted a reply to your Reddit thread: https://old.reddit.com/r/Anki/comments/8zjo3a/visual_cue_for_one_card_of_note_with_multiple/e2jozts/

Closing this issue report as it's not directly related to Image Occlusion Enhanced.
