### ISSUE TITLE
Multiple Blank Cards gets created

### ISSUE THREAD

**Issue by revant1234** [glutanimate/image-occlusion-enhanced#81]
## Prerequisite checklist

* [ done] In case of a bug: Have you tried restarting Anki?
* [ done] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [ done] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [ done] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
I use surface pro 3.When i occlude even 1 thing with surface pen multiple blank cards gets created.
I finally found out that for some reason addon is creating small occlusions at the top left hand corner which is making multiple flashcards.
![image](https://user-images.githubusercontent.com/6932718/45676281-037af380-bb4f-11e8-95ff-e41ed80f1e53.png)
I have to delete them now after occluding everything and then add cards but this didn't happened in previous versions.
This also doesn't happen if i use mouse/trackpad or use right click on pen to occlude.

## Version information

**Anki**
Version 2.0.52
Qt 4.8.4 PyQt 4.10
**System**

- Operating system: Windows
- Version: 10
-surface pro3

**Comment by glutanimate** [comment]
Hi,

Thanks for the detailed report. This is fixed in the add-on's latest release (Anki 2.1 only for now).

See here: #40

**Comment by revant1234** [comment]
thank you sir for helping out i tried it out yes it is solved there but in that version surface pen starts draging instead of making a rectangle/occlusion,images don't open maximized and the fit button also doesn't work.
I guess these are expected with beta version.
