### ISSUE TITLE
Suggestion : add shortcut for "toggle mask"

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [glutanimate/image-occlusion-enhanced#97]
## Prerequisite checklist
* [ X ] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [ X ] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [ X ] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
add a shortcut to toggle masks, I propose G or H

## Version information

**Anki 2.1.9**
Version 2.1.9 (ae67c976)
Qt 5.12.1 PyQt 5.11.3

**Comment by glutanimate** [comment]
Hi. Thanks for the suggestion! However, this should already be working: https://github.com/glutanimate/image-occlusion-enhanced/blob/master/src/image_occlusion_enhanced/main.py#L206-L223

The hint hotkey is set to G. If that doesn't work you might either be using an old card template or there might be interferences with other add-on at play.

**Comment by thiswillbeyourgithub** [comment]
It indeed is working after disabling the addon [hint hotkeys](https://ankiweb.net/shared/info/1844908621)

But I don't think I heard of this shortcut in the wiki, I think it would be a good idea.

You truly are the best.

**Comment by stnk8** [comment]
I was able to get this working after disabling hint hotkeys, but it only works the first time I use it.  If I go back out to the decks and back in, its stops working.  Any idea why?

**Comment by thiswillbeyourgithub** [comment]
I have the same kind of problem. It stops working after a few minutes and I can't be certain of the reason. It's very annoying for my anatomy courses :/

**Comment by stnk8** [comment]
I played around with it and found that deleting the right hand reviews for jkl got rid of the problem.  I changed the shortcuts in the customize keyboard shortcuts add on and it seems to be working fine for now (knock on wood..).   I also re-enabled hint hotkeys and it seems to work

**Comment by thiswillbeyourgithub** [comment]
Thanks, I removed "hand reviews for jkl" and added "keyboard shortcuts" and it's been working fine all day. Thanks !
