### ISSUE TITLE
Error message when editing cards in place

### ISSUE THREAD

**Issue by BUG9876** [glutanimate/image-occlusion-enhanced#99]
## Prerequisite checklist

* [x] In case of a bug: Have you tried restarting Anki?
* [x] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [x] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [x] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
I receive an error message when editing cards in place. Scenario by which this happens: 1. Let's say I create 10 flashcards on the same image (no problem here). 2. I review/study the 10 flashcards (no problem here) 3. Now as I review the flashcards, I may decide to edit them, specifically to group 3 of the 10 flashcards (I am able to group the 3 elements, then when I click edit cards > answer yes to "are you sure you want to...">I get the following error message:

![error when editing cards in place](https://user-images.githubusercontent.com/49581805/56076131-f1c69b00-5d81-11e9-884c-43e99a0e2cf7.png)

[Be as specific as possible. Provide screenshots if you think they can help.]

## How can we reproduce the problem?
See scenario above.
[What were you doing when the problem occurred?]

1. I would be reviewing cards
2. After I master some cards alone, I seek to group them for efficiency
3. Attempting to group cards and generate a new flashcard renders an error message

**Expected behavior:** [What you expected to happen]
Cards successfully edited
**Actual behavior:** [What actually happened]
Error message
**Reproducible?:** [Can you reliably reproduce the issue by following the steps above?]
Yes
## Version information

**Anki**

[Please head to *Help* → *About Anki* and Paste the version string here, e.g.:]

[Version 2.0.47]
[Qt 4.8.1 PyQt 4.9.1]

**System**

- Operating system: [Windows/macOS/Linux]
- Version: [e.g. 10, High Sierra, Ubuntu 18.04]

**Comment by BUG9876** [comment]
Actually, the elements seem to be successful grouped but the error message appears nevertheless

**Comment by zjosua** [comment]
@BUG9876 this has already been adressed in #88, but is not released yet.

**Comment by glutanimate** [comment]
Thanks for the detailed report, @BUG9876, and thanks again for chiming in, @zjosua. I've just pushed [v1.3.0-alpha4](https://github.com/glutanimate/image-occlusion-enhanced/releases) to the releases page which includes the fix. Please let me know if you run into any issues with it.

**Comment by glutanimate** [comment]
v1.3.0-alpha4 is now also live on AnkiWeb.
